"""
excludes.py — the ONE exclude list, projected everywhere it must reach.

RECEIVES:  the target folder (reads the user-editable .secignore in it)
           and the report/output folder (so we never scan our own output)
PRODUCES:  skip rules for collector.py  +  each external tool's native
           ignore format (semgrep --exclude args, trivy --skip-dirs args,
           a generated gitleaks config with path allowlists)
CALLED BY: main.py (once, at startup) and collector.py (during the walk)

WHY THIS EXISTS: external tools do their own filesystem walk, so an
internal Python ignore list cannot protect them. One list, three native
projections — "the tool flags its own cache/report files" becomes
impossible by construction, not by care.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from fnmatch import fnmatch
from pathlib import Path

# The single source of truth. Directory NAMES skipped anywhere they appear.
EXCLUDED_DIR_NAMES = {
    ".git",
    ".hg",
    ".svn",
    "node_modules",
    "vendor",
    "__pycache__",
    ".venv",
    "venv",
    "dist",
    "build",
    ".idea",
    ".vscode",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
}

SECIGNORE_NAME = ".secignore"  # user-editable, one glob pattern per line


@dataclass
class Excludes:
    """The prepared exclude rules for one run. Create via prepare()."""

    target: Path
    report_dir: Path
    dir_names: set[str] = field(default_factory=lambda: set(EXCLUDED_DIR_NAMES))
    user_patterns: list[str] = field(default_factory=list)  # from .secignore

    # ---- used by collector.py (our own walk) -------------------------------

    def skip_dir(self, dir_path: Path) -> bool:
        if dir_path.name in self.dir_names:
            return True
        if self._is_inside_report_dir(dir_path):
            return True
        return self._matches_user_pattern(dir_path)

    def skip_file(self, file_path: Path) -> bool:
        if self._is_inside_report_dir(file_path):
            return True
        return self._matches_user_pattern(file_path)

    # ---- projections: the SAME list in each external tool's native format --

    def semgrep_args(self) -> list[str]:
        """Semgrep's native exclude mechanism: repeated --exclude flags."""
        args: list[str] = []
        for name in sorted(self.dir_names) + self.user_patterns:
            args += ["--exclude", name]
        args += ["--exclude", self.report_dir.name]
        return args

    def trivy_args(self) -> list[str]:
        """Trivy's native mechanism: --skip-dirs (comma-joined)."""
        dirs = sorted(self.dir_names) + [self.report_dir.name]
        return ["--skip-dirs", ",".join(dirs)]

    def gitleaks_config_path(self) -> Path:
        """Gitleaks' native mechanism: a config whose allowlist paths are
        ignored. We extend the default rules and add our list as path
        regexes. The file is written into the report dir (itself excluded).
        """
        self.report_dir.mkdir(parents=True, exist_ok=True)
        config_path = self.report_dir / "gitleaks_config.toml"

        path_regexes = [self._dir_regex(n) for n in sorted(self.dir_names)]
        path_regexes.append(self._dir_regex(self.report_dir.name))
        for pattern in self.user_patterns:
            path_regexes.append(re.escape(pattern.strip("/")))

        lines = [
            "# Generated by excludes.py — one shared exclude list,",
            "# projected into gitleaks' native format. Do not edit.",
            "[extend]",
            "useDefault = true",
            "",
            "[allowlist]",
            "paths = [",
        ]
        for regex in path_regexes:
            lines.append(f"    '''{regex}''',")
        lines.append("]")
        config_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return config_path

    # ---- internals ---------------------------------------------------------

    @staticmethod
    def _dir_regex(name: str) -> str:
        """A Go-compatible regex matching `name` as any path segment."""
        return r"(^|[\\/])" + re.escape(name) + r"([\\/]|$)"

    def _is_inside_report_dir(self, path: Path) -> bool:
        try:
            path.resolve().relative_to(self.report_dir.resolve())
            return True
        except ValueError:
            return False

    def _matches_user_pattern(self, path: Path) -> bool:
        try:
            relative = path.resolve().relative_to(self.target.resolve())
        except ValueError:
            return False
        rel_posix = relative.as_posix()
        for pattern in self.user_patterns:
            clean = pattern.strip("/")
            if fnmatch(rel_posix, clean) or fnmatch(path.name, clean):
                return True
            # "docs/" style patterns mean: skip everything under that folder
            if rel_posix.startswith(clean + "/"):
                return True
        return False


def prepare(target: Path, report_dir: Path) -> Excludes:
    """Build the exclude rules for this run. Called ONCE by main.py,
    before anything is collected or scanned."""
    excludes = Excludes(target=target, report_dir=report_dir)

    secignore = target / SECIGNORE_NAME
    if secignore.is_file():
        for raw_line in secignore.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if line and not line.startswith("#"):
                excludes.user_patterns.append(line)

    return excludes
